phrase:
  access_token: 7d97939e2cc6a6cc5bb51312baa04ca5ffb934b555495a6a656b14420e24fbdf
  project_id: f220a09b66423922daede0b64352f350
  push:
    sources:
    - file: ./Wishlist/Resources/Localizable.xcstrings
      params:
        file_format: strings_catalog
  pull:
    targets:
    - file: ./Wishlist/Resources/Localizable.xcstrings
      params:
        file_format: strings_catalog
